name: Flask CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Pytest and Generate Report (Кейс 7, 8)
      run: |
        pytest --html=report.html --self-contained-html
        
    - name: Upload HTML Test Report Artifact
      uses: actions/upload-artifact@v4
      with:
        name: html-report
        path: report.html